import { AssessmentQuestion, Challenge, Achievement, Quest, WellnessProfile, ChallengeQuestion, InventoryItem } from './types';

// Wellness Challenge Questions - Organized by Interactive Categories
export const wellnessQuestions: ChallengeQuestion[] = [
  // FITNESS SPRINT CHALLENGES
  {
    id: 'fit-sprint-1',
    question: 'You\'re starting a 5K run. What heart rate zone should you target for optimal endurance?',
    options: ['50-60% max HR', '60-70% max HR', '70-80% max HR', '90-100% max HR'],
    correctAnswer: 2,
    explanation: '70-80% of your maximum heart rate is the ideal zone for building endurance and cardiovascular fitness.',
    difficulty: 'medium',
  },
  {
    id: 'fit-sprint-2',
    question: 'How many calories does a 30-minute moderate jog typically burn?',
    options: ['100-150 calories', '200-350 calories', '400-500 calories', '600-700 calories'],
    correctAnswer: 1,
    explanation: 'A 30-minute moderate jog burns approximately 200-350 calories depending on weight and speed.',
    difficulty: 'medium',
  },
  {
    id: 'fit-sprint-3',
    question: 'What is the ideal running cadence (steps per minute) for efficiency?',
    options: ['140-150 SPM', '160-170 SPM', '180-190 SPM', '200-210 SPM'],
    correctAnswer: 2,
    explanation: '180 steps per minute is considered the optimal cadence for most runners to reduce injury risk.',
    difficulty: 'hard',
  },
  
  // FITNESS STRENGTH CHALLENGES
  {
    id: 'fit-str-1',
    question: 'How long should you rest between heavy strength training sets?',
    options: ['30 seconds', '1 minute', '2-3 minutes', '5 minutes'],
    correctAnswer: 2,
    explanation: '2-3 minutes of rest allows for full ATP recovery, maximizing strength gains in heavy lifting.',
    difficulty: 'medium',
  },
  {
    id: 'fit-str-2',
    question: 'Which exercise works the most muscle groups simultaneously?',
    options: ['Bicep curls', 'Leg extensions', 'Deadlifts', 'Calf raises'],
    correctAnswer: 2,
    explanation: 'Deadlifts are a compound exercise engaging back, glutes, hamstrings, core, and grip simultaneously.',
    difficulty: 'easy',
  },
  {
    id: 'fit-str-3',
    question: 'What does "progressive overload" mean in strength training?',
    options: ['Training until failure', 'Gradually increasing workout intensity', 'Lifting as heavy as possible', 'Working out every day'],
    correctAnswer: 1,
    explanation: 'Progressive overload means gradually increasing weight, reps, or intensity to continuously challenge muscles.',
    difficulty: 'easy',
  },
  
  // FITNESS FLEXIBILITY
  {
    id: 'fit-flex-1',
    question: 'How long should you hold a static stretch?',
    options: ['5-10 seconds', '15-30 seconds', '45-60 seconds', '2 minutes'],
    correctAnswer: 1,
    explanation: 'Holding a static stretch for 15-30 seconds is optimal for improving flexibility safely.',
    difficulty: 'easy',
  },
  {
    id: 'fit-flex-2',
    question: 'What type of stretching is best before high-intensity exercise?',
    options: ['Static stretching', 'Dynamic stretching', 'PNF stretching', 'No stretching'],
    correctAnswer: 1,
    explanation: 'Dynamic stretching prepares muscles for activity by increasing blood flow and range of motion.',
    difficulty: 'medium',
  },

  
  // NUTRITION MEAL PLANNING
  {
    id: 'nut-plan-1',
    question: 'You need 150g of protein daily. Which meal combo provides the most?',
    options: ['3 chicken breasts (90g)', '6 eggs + 2 cups Greek yogurt (75g)', '200g salmon + 1 cup quinoa (60g)', '2 protein shakes + 1 steak (120g)'],
    correctAnswer: 3,
    explanation: 'Combining protein sources like shakes (50g) and steak (70g) efficiently meets high protein goals.',
    difficulty: 'hard',
  },
  {
    id: 'nut-plan-2',
    question: 'What macronutrient ratio is ideal for weight loss?',
    options: ['70% carbs, 20% protein, 10% fat', '40% carbs, 30% protein, 30% fat', '10% carbs, 45% protein, 45% fat', '33% each'],
    correctAnswer: 1,
    explanation: 'A 40-30-30 ratio balances satiety, energy, and muscle preservation during weight loss.',
    difficulty: 'medium',
  },
  {
    id: 'nut-plan-3',
    question: 'You\'re planning pre-workout nutrition. What should you eat 2 hours before?',
    options: ['High fat meal', 'Complex carbs + moderate protein', 'Simple sugars only', 'Heavy protein shake'],
    correctAnswer: 1,
    explanation: 'Complex carbs provide sustained energy while moderate protein prevents muscle breakdown.',
    difficulty: 'medium',
  },
  
  // NUTRITION IQ  
  {
    id: 'nut-iq-1',
    question: 'Which has more protein per 100g?',
    options: ['Chicken breast (31g)', 'Lentils (9g)', 'Almonds (21g)', 'Greek yogurt (10g)'],
    correctAnswer: 0,
    explanation: 'Chicken breast is one of the leanest, highest protein foods at 31g per 100g serving.',
    difficulty: 'easy',
  },
  {
    id: 'nut-iq-2',
    question: 'What\'s the glycemic index value range for "low GI" foods?',
    options: ['0-35', '0-55', '0-70', '0-85'],
    correctAnswer: 1,
    explanation: 'Foods with a GI of 55 or less are considered low glycemic and cause smaller blood sugar spikes.',
    difficulty: 'hard',
  },
  {
    id: 'nut-iq-3',
    question: 'How many grams of fiber should adults consume daily?',
    options: ['10-15g', '25-30g', '40-45g', '50-60g'],
    correctAnswer: 1,
    explanation: 'Adults should consume 25-30g of fiber daily for optimal digestive health.',
    difficulty: 'medium',
  },
  
  // NUTRITION HYDRATION
  {
    id: 'nut-hydro-1',
    question: 'You lost 2 pounds during a workout. How much water should you drink?',
    options: ['8 oz (1 cup)', '16 oz (2 cups)', '24-32 oz (3-4 cups)', '48 oz (6 cups)'],
    correctAnswer: 2,
    explanation: 'Drink 24-32 oz of water for every pound lost during exercise to rehydrate properly.',
    difficulty: 'medium',
  },
  {
    id: 'nut-hydro-2',
    question: 'What color should your urine be if properly hydrated?',
    options: ['Clear like water', 'Pale yellow', 'Dark yellow', 'Amber'],
    correctAnswer: 1,
    explanation: 'Pale yellow urine indicates proper hydration; clear means over-hydration, dark means dehydration.',
    difficulty: 'easy',
  },

  // MIND FOCUS GAMES - Concentration & Memory
  {
    id: 'mind-focus-1',
    question: 'Quick! Memorize: 7-3-9-2-5. What was the 4th number?',
    options: ['3', '2', '9', '5'],
    correctAnswer: 1,
    explanation: 'The sequence was 7-3-9-2-5, making 2 the fourth number. This tests working memory!',
    difficulty: 'easy',
  },
  {
    id: 'mind-focus-2',
    question: 'Focus test: Which word was NOT in this list? (Apple, Book, Chair, Lamp)',
    options: ['Table', 'Book', 'Lamp', 'Apple'],
    correctAnswer: 0,
    explanation: 'Table was not in the original list. This tests attention to detail and short-term memory.',
    difficulty: 'easy',
  },
  {
    id: 'mind-focus-3',
    question: 'Pattern recognition: 2, 4, 8, 16, __. What comes next?',
    options: ['24', '32', '28', '20'],
    correctAnswer: 1,
    explanation: 'Each number doubles: 2×2=4, 4×2=8, 8×2=16, 16×2=32. This tests pattern recognition.',
    difficulty: 'medium',
  },
  {
    id: 'mind-focus-4',
    question: 'How many windows are in your home? (Estimate quickly - this tests spatial memory)',
    options: ['Memory recall exercise', 'Testing visualization', 'Assessing awareness', 'All correct'],
    correctAnswer: 3,
    explanation: 'This exercise activates spatial memory and mental visualization - the act of counting is the test!',
    difficulty: 'easy',
  },
  
  // MIND BREATHING TECHNIQUES
  {
    id: 'mind-breath-1',
    question: 'For the 4-7-8 breathing technique, how long do you hold your breath?',
    options: ['4 seconds', '7 seconds', '8 seconds', '10 seconds'],
    correctAnswer: 1,
    explanation: 'The 4-7-8 technique: Inhale 4 seconds, hold 7 seconds, exhale 8 seconds for deep relaxation.',
    difficulty: 'medium',
  },
  {
    id: 'mind-breath-2',
    question: 'What breathing rate (breaths per minute) promotes relaxation?',
    options: ['20-25 BPM', '15-20 BPM', '10-12 BPM', '5-6 BPM'],
    correctAnswer: 3,
    explanation: 'Slowing breath to 5-6 breaths per minute activates the parasympathetic nervous system.',
    difficulty: 'hard',
  },
  {
    id: 'mind-breath-3',
    question: 'Box breathing involves equal counts for inhale, hold, exhale, hold. What count is recommended?',
    options: ['2 seconds', '4 seconds', '6 seconds', '8 seconds'],
    correctAnswer: 1,
    explanation: 'Box breathing uses 4 seconds for each phase (4-4-4-4), used by Navy SEALs for stress management.',
    difficulty: 'medium',
  },
  
  // MIND MEDITATION MASTERY
  {
    id: 'mind-med-1',
    question: 'In body scan meditation, where do you typically start?',
    options: ['Head', 'Toes/feet', 'Chest/heart', 'Hands'],
    correctAnswer: 1,
    explanation: 'Body scan meditation usually starts at the toes and moves upward, systematically relaxing each part.',
    difficulty: 'easy',
  },
  {
    id: 'mind-med-2',
    question: 'What\'s the difference between mindfulness and concentration meditation?',
    options: ['No difference', 'Mindfulness observes, concentration focuses', 'One is harder', 'One uses mantras'],
    correctAnswer: 1,
    explanation: 'Mindfulness observes thoughts without attachment; concentration meditation focuses on a single object.',
    difficulty: 'hard',
  },
  {
    id: 'mind-med-3',
    question: 'How long does it take to form a daily meditation habit?',
    options: ['7 days', '21 days', '66 days', '100 days'],
    correctAnswer: 2,
    explanation: 'Research shows it takes an average of 66 days to form a new habit automatically.',
    difficulty: 'medium',
  },
  
  // MIND STRESS MANAGEMENT
  {
    id: 'mind-stress-1',
    question: 'What hormone is released during acute stress?',
    options: ['Serotonin', 'Dopamine', 'Cortisol', 'Melatonin'],
    correctAnswer: 2,
    explanation: 'Cortisol is the primary stress hormone, released to prepare the body for fight-or-flight.',
    difficulty: 'easy',
  },
  {
    id: 'mind-stress-2',
    question: 'Which technique helps reset your nervous system in 30 seconds?',
    options: ['Deep breathing', 'Cold water on face', 'Running', 'Screaming'],
    correctAnswer: 1,
    explanation: 'The dive reflex: Splashing cold water on your face quickly activates the parasympathetic response.',
    difficulty: 'medium',
  },
  {
    id: 'mind-stress-3',
    question: 'What percentage of worry thoughts never actually happen?',
    options: ['25%', '50%', '75%', '85%'],
    correctAnswer: 3,
    explanation: 'Studies show 85% of what we worry about never occurs, highlighting the value of mindfulness.',
    difficulty: 'hard',
  },

  // SLEEP OPTIMIZATION
  {
    id: 'sleep-opt-1',
    question: 'What\'s the ideal time to go to bed if you wake at 6 AM?',
    options: ['9:00 PM', '10:00 PM', '10:30 PM', '11:30 PM'],
    correctAnswer: 2,
    explanation: 'Going to bed at 10:30 PM allows for 7.5 hours of sleep (5 complete 90-minute sleep cycles).',
    difficulty: 'medium',
  },
  {
    id: 'sleep-opt-2',
    question: 'How long is one complete sleep cycle?',
    options: ['60 minutes', '75 minutes', '90 minutes', '120 minutes'],
    correctAnswer: 2,
    explanation: 'A complete sleep cycle is approximately 90 minutes, cycling through all sleep stages.',
    difficulty: 'easy',
  },
  {
    id: 'sleep-opt-3',
    question: 'What\'s the best room temperature for optimal sleep?',
    options: ['70-75°F', '65-68°F', '60-63°F', '55-58°F'],
    correctAnswer: 1,
    explanation: 'A cooler room temperature of 65-68°F (18-20°C) promotes deeper, more restful sleep.',
    difficulty: 'easy',
  },
  
  // SLEEP SCIENCE & RECOVERY
  {
    id: 'sleep-sci-1',
    question: 'During which sleep stage does most muscle recovery occur?',
    options: ['Light sleep', 'REM sleep', 'Deep sleep', 'Stage 1'],
    correctAnswer: 2,
    explanation: 'Deep sleep (Stage 3) is when growth hormone is released for muscle repair and recovery.',
    difficulty: 'medium',
  },
  {
    id: 'sleep-sci-2',
    question: 'What percentage of sleep should be deep sleep?',
    options: ['5-10%', '13-23%', '30-40%', '50-60%'],
    correctAnswer: 1,
    explanation: 'Healthy adults spend 13-23% of sleep in deep sleep, crucial for physical restoration.',
    difficulty: 'hard',
  },
  {
    id: 'sleep-sci-3',
    question: 'How long before bed should you stop using screens?',
    options: ['15 minutes', '30 minutes', '1 hour', '2 hours'],
    correctAnswer: 2,
    explanation: 'Stopping screen use 1 hour before bed reduces blue light exposure and improves melatonin production.',
    difficulty: 'easy',
  },
  
  // SLEEP HABITS & HYGIENE
  {
    id: 'sleep-hab-1',
    question: 'What\'s the maximum recommended nap duration to avoid sleep inertia?',
    options: ['10 minutes', '20 minutes', '45 minutes', '90 minutes'],
    correctAnswer: 1,
    explanation: 'A 20-minute power nap refreshes without causing grogginess from entering deep sleep.',
    difficulty: 'medium',
  },
  {
    id: 'sleep-hab-2',
    question: 'When should you stop drinking caffeine to ensure good sleep?',
    options: ['2 hours before bed', '4 hours before bed', '6 hours before bed', '8 hours before bed'],
    correctAnswer: 2,
    explanation: 'Caffeine has a 5-6 hour half-life, so stopping 6+ hours before bed prevents sleep disruption.',
    difficulty: 'easy',
  },
  {
    id: 'sleep-hab-3',
    question: 'Which color light is best for evening use?',
    options: ['Blue light', 'White light', 'Red/amber light', 'Green light'],
    correctAnswer: 2,
    explanation: 'Red or amber light doesn\'t suppress melatonin production like blue light does.',
    difficulty: 'easy',
  },
  
  // SLEEP DISORDERS AWARENESS
  {
    id: 'sleep-dis-1',
    question: 'What\'s the most common sleep disorder?',
    options: ['Sleep apnea', 'Insomnia', 'Narcolepsy', 'Restless leg syndrome'],
    correctAnswer: 1,
    explanation: 'Insomnia affects 30% of adults, making it the most common sleep disorder worldwide.',
    difficulty: 'easy',
  },
  {
    id: 'sleep-dis-2',
    question: 'How many times per hour defines moderate sleep apnea?',
    options: ['5-10 events', '15-30 events', '35-50 events', '50+ events'],
    correctAnswer: 1,
    explanation: 'Moderate sleep apnea is 15-30 breathing interruptions per hour; severe is 30+.',
    difficulty: 'hard',
  },
  {
    id: 'sleep-dis-3',
    question: 'What\'s the clinical term for difficulty falling asleep?',
    options: ['Sleep onset insomnia', 'Sleep maintenance insomnia', 'Terminal insomnia', 'Parasomnia'],
    correctAnswer: 0,
    explanation: 'Sleep onset insomnia specifically refers to difficulty initiating sleep at bedtime.',
    difficulty: 'medium',
  },
];

// Assessment Questions
export const assessmentQuestions: AssessmentQuestion[] = [
  {
    id: 'q1',
    question: 'How would you describe your current fitness level?',
    type: 'multiple-choice',
    category: 'fitness',
    options: [
      { 
        id: 'q1-a', 
        text: 'Sedentary - I rarely exercise', 
        value: 1, 
        profile: ['beginner'] 
      },
      { 
        id: 'q1-b', 
        text: 'Lightly active - I exercise 1-2 times per week', 
        value: 2, 
        profile: ['beginner', 'balanced'] 
      },
      { 
        id: 'q1-c', 
        text: 'Moderately active - I exercise 3-4 times per week', 
        value: 3, 
        profile: ['active', 'balanced'] 
      },
      { 
        id: 'q1-d', 
        text: 'Very active - I exercise 5+ times per week', 
        value: 4, 
        profile: ['athlete', 'active'] 
      },
    ],
  },
  {
    id: 'q2',
    question: 'How important is nutrition in your daily routine?',
    type: 'scale',
    category: 'nutrition',
    options: [
      { 
        id: 'q2-a', 
        text: 'Not important - I eat whatever is convenient', 
        value: 1, 
        profile: ['beginner'] 
      },
      { 
        id: 'q2-b', 
        text: 'Somewhat important - I try to eat healthy sometimes', 
        value: 2, 
        profile: ['active'] 
      },
      { 
        id: 'q2-c', 
        text: 'Very important - I plan most of my meals', 
        value: 3, 
        profile: ['health-focused', 'balanced'] 
      },
      { 
        id: 'q2-d', 
        text: 'Extremely important - I track my nutrition carefully', 
        value: 4, 
        profile: ['health-focused', 'athlete'] 
      },
    ],
  },
  {
    id: 'q3',
    question: 'How often do you practice mindfulness or meditation?',
    type: 'multiple-choice',
    category: 'mindfulness',
    options: [
      { 
        id: 'q3-a', 
        text: 'Never - I haven\'t tried it', 
        value: 1, 
        profile: ['beginner', 'athlete'] 
      },
      { 
        id: 'q3-b', 
        text: 'Rarely - A few times a month', 
        value: 2, 
        profile: ['active'] 
      },
      { 
        id: 'q3-c', 
        text: 'Regularly - A few times a week', 
        value: 3, 
        profile: ['balanced', 'health-focused'] 
      },
      { 
        id: 'q3-d', 
        text: 'Daily - It\'s part of my routine', 
        value: 4, 
        profile: ['health-focused', 'balanced'] 
      },
    ],
  },
  {
    id: 'q4',
    question: 'How would you rate your sleep quality?',
    type: 'scale',
    category: 'sleep',
    options: [
      { 
        id: 'q4-a', 
        text: 'Poor - I struggle to sleep well', 
        value: 1, 
        profile: ['beginner', 'health-focused'] 
      },
      { 
        id: 'q4-b', 
        text: 'Fair - Sleep is inconsistent', 
        value: 2, 
        profile: ['active', 'health-focused'] 
      },
      { 
        id: 'q4-c', 
        text: 'Good - I get decent sleep most nights', 
        value: 3, 
        profile: ['balanced', 'active'] 
      },
      { 
        id: 'q4-d', 
        text: 'Excellent - I have a solid sleep routine', 
        value: 4, 
        profile: ['balanced', 'athlete'] 
      },
    ],
  },
  {
    id: 'q5',
    question: 'What are your main wellness goals? (Select all that apply)',
    type: 'multi-select',
    category: 'fitness',
    options: [
      { 
        id: 'q5-a', 
        text: 'Build strength and muscle', 
        value: 3, 
        profile: ['athlete', 'active'] 
      },
      { 
        id: 'q5-b', 
        text: 'Improve cardiovascular health', 
        value: 3, 
        profile: ['athlete', 'active', 'health-focused'] 
      },
      { 
        id: 'q5-c', 
        text: 'Lose or maintain weight', 
        value: 2, 
        profile: ['health-focused', 'balanced'] 
      },
      { 
        id: 'q5-d', 
        text: 'Reduce stress and anxiety', 
        value: 2, 
        profile: ['health-focused', 'balanced', 'beginner'] 
      },
      { 
        id: 'q5-e', 
        text: 'Establish consistent healthy habits', 
        value: 2, 
        profile: ['beginner', 'balanced'] 
      },
    ],
  },
];

// Sample Challenges - Interactive Wellness Tests
export const sampleChallenges: Challenge[] = [
  // Daily Challenges - Quick Tests
  {
    id: 'chal-daily-1',
    name: '🏃 Fitness Sprint Challenge',
    description: 'Test your fitness knowledge with 5 sprint and cardio questions',
    type: 'fitness',
    tier: 'daily',
    difficulty: 'normal',
    target: 5,
    current: 0,
    unit: 'questions',
    startDate: new Date(),
    endDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    reward: {
      experience: 200,
      gold: 100,
      comboBonus: 1.1,
    },
    participants: 5243,
    completed: false,
    accepted: false,
    inProgress: false,
    questionsAnswered: 0,
    correctAnswers: 0,
    questions: [
      wellnessQuestions.find(q => q.id === 'fit-sprint-1')!,
      wellnessQuestions.find(q => q.id === 'fit-sprint-2')!,
      wellnessQuestions.find(q => q.id === 'fit-sprint-3')!,
      wellnessQuestions.find(q => q.id === 'fit-str-1')!,
      wellnessQuestions.find(q => q.id === 'fit-flex-1')!,
    ],
    milestones: [
      { progress: 50, reward: 50 },
      { progress: 100, reward: 50 },
    ],
  },
  {
    id: 'chal-daily-2',
    name: '🧠 Mind Focus Challenge',
    description: 'Test your concentration with memory and focus exercises',
    type: 'mindfulness',
    tier: 'daily',
    difficulty: 'normal',
    target: 5,
    current: 0,
    unit: 'questions',
    startDate: new Date(),
    endDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    reward: {
      experience: 150,
      gold: 75,
      comboBonus: 1.15,
    },
    participants: 3421,
    completed: false,
    accepted: false,
    inProgress: false,
    questionsAnswered: 0,
    correctAnswers: 0,
    questions: [
      wellnessQuestions.find(q => q.id === 'mind-focus-1')!,
      wellnessQuestions.find(q => q.id === 'mind-focus-2')!,
      wellnessQuestions.find(q => q.id === 'mind-focus-3')!,
      wellnessQuestions.find(q => q.id === 'mind-focus-4')!,
      wellnessQuestions.find(q => q.id === 'mind-breath-1')!,
    ],
    milestones: [
      { progress: 50, reward: 50 },
      { progress: 100, reward: 50 },
    ],
  },
  {
    id: 'chal-daily-3',
    name: '🥗 Nutrition IQ Test',
    description: 'Prove your nutrition knowledge with meal planning questions',
    type: 'nutrition',
    tier: 'daily',
    difficulty: 'hard',
    target: 5,
    current: 0,
    unit: 'questions',
    startDate: new Date(),
    endDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    reward: {
      experience: 250,
      gold: 150,
      comboBonus: 1.25,
    },
    participants: 2156,
    completed: false,
    accepted: false,
    inProgress: false,
    questionsAnswered: 0,
    correctAnswers: 0,
    questions: [
      wellnessQuestions.find(q => q.id === 'nut-plan-1')!,
      wellnessQuestions.find(q => q.id === 'nut-plan-2')!,
      wellnessQuestions.find(q => q.id === 'nut-iq-1')!,
      wellnessQuestions.find(q => q.id === 'nut-iq-2')!,
      wellnessQuestions.find(q => q.id === 'nut-hydro-1')!,
    ],
    modifier: 'perfect-only',
    milestones: [
      { progress: 50, reward: 75 },
      { progress: 100, reward: 75 },
    ],
  },

  // Weekly Challenges - Comprehensive Tests
  {
    id: 'chal-weekly-1',
    name: '😴 Sleep Optimization Mastery',
    description: 'Master sleep science with our comprehensive sleep challenge',
    type: 'sleep',
    tier: 'weekly',
    difficulty: 'normal',
    target: 8,
    current: 0,
    unit: 'questions',
    startDate: new Date(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    reward: {
      experience: 800,
      gold: 400,
      achievement: 'ach-sleep-master',
    },
    participants: 8234,
    completed: false,
    accepted: false,
    inProgress: false,
    questionsAnswered: 0,
    correctAnswers: 0,
    questions: [
      wellnessQuestions.find(q => q.id === 'sleep-opt-1')!,
      wellnessQuestions.find(q => q.id === 'sleep-opt-2')!,
      wellnessQuestions.find(q => q.id === 'sleep-opt-3')!,
      wellnessQuestions.find(q => q.id === 'sleep-sci-1')!,
      wellnessQuestions.find(q => q.id === 'sleep-sci-2')!,
      wellnessQuestions.find(q => q.id === 'sleep-hab-1')!,
      wellnessQuestions.find(q => q.id === 'sleep-hab-2')!,
      wellnessQuestions.find(q => q.id === 'sleep-dis-1')!,
    ],
    milestones: [
      { progress: 25, reward: 100 },
      { progress: 50, reward: 150 },
      { progress: 75, reward: 200 },
    ],
  },
  {
    id: 'chal-weekly-2',
    name: '💪 Complete Fitness Assessment',
    description: 'Test your knowledge across strength, cardio, and flexibility',
    type: 'fitness',
    tier: 'weekly',
    difficulty: 'hard',
    target: 8,
    current: 0,
    unit: 'questions',
    startDate: new Date(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    reward: {
      experience: 1000,
      gold: 500,
      achievement: 'ach-fitness-guru',
    },
    participants: 3421,
    completed: false,
    accepted: false,
    inProgress: false,
    questionsAnswered: 0,
    correctAnswers: 0,
    questions: [
      wellnessQuestions.find(q => q.id === 'fit-sprint-1')!,
      wellnessQuestions.find(q => q.id === 'fit-sprint-3')!,
      wellnessQuestions.find(q => q.id === 'fit-str-1')!,
      wellnessQuestions.find(q => q.id === 'fit-str-2')!,
      wellnessQuestions.find(q => q.id === 'fit-str-3')!,
      wellnessQuestions.find(q => q.id === 'fit-flex-1')!,
      wellnessQuestions.find(q => q.id === 'fit-flex-2')!,
      wellnessQuestions.find(q => q.id === 'fit-sprint-2')!,
    ],
    modifier: 'speed-run',
    milestones: [
      { progress: 20, reward: 100 },
      { progress: 40, reward: 150 },
      { progress: 60, reward: 150 },
      { progress: 80, reward: 200 },
    ],
  },

  // Weekly Challenges continuation
  {
    id: 'chal-weekly-3',
    name: '🎯 Mind & Stress Mastery',
    description: 'Master breathing techniques and stress management',
    type: 'mindfulness',
    tier: 'weekly',
    difficulty: 'hard',
    target: 10,
    current: 0,
    unit: 'questions',
    startDate: new Date(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    reward: {
      experience: 900,
      gold: 450,
      achievement: 'ach-zen-master',
    },
    participants: 2987,
    completed: false,
    accepted: false,
    inProgress: false,
    questionsAnswered: 0,
    correctAnswers: 0,
    questions: [
      wellnessQuestions.find(q => q.id === 'mind-focus-1')!,
      wellnessQuestions.find(q => q.id === 'mind-focus-2')!,
      wellnessQuestions.find(q => q.id === 'mind-focus-3')!,
      wellnessQuestions.find(q => q.id === 'mind-breath-1')!,
      wellnessQuestions.find(q => q.id === 'mind-breath-2')!,
      wellnessQuestions.find(q => q.id === 'mind-breath-3')!,
      wellnessQuestions.find(q => q.id === 'mind-med-1')!,
      wellnessQuestions.find(q => q.id === 'mind-stress-1')!,
      wellnessQuestions.find(q => q.id === 'mind-stress-2')!,
      wellnessQuestions.find(q => q.id === 'mind-stress-3')!,
    ],
    modifier: 'combo-chain',
    milestones: [
      { progress: 33, reward: 125 },
      { progress: 66, reward: 175 },
      { progress: 100, reward: 200 },
    ],
  },

  // Seasonal Challenges - Ultimate Tests
  {
    id: 'chal-seasonal-1',
    name: '🏆 Ultimate Wellness Challenge',
    description: 'Master all wellness categories with 15 challenging questions',
    type: 'fitness',
    tier: 'seasonal',
    difficulty: 'extreme',
    target: 15,
    current: 0,
    unit: 'questions',
    startDate: new Date(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    reward: {
      experience: 2000,
      gold: 1000,
      achievement: 'ach-wellness-master',
    },
    participants: 15234,
    completed: false,
    accepted: false,
    inProgress: false,
    questionsAnswered: 0,
    correctAnswers: 0,
    questions: [
      wellnessQuestions.find(q => q.id === 'fit-sprint-3')!,
      wellnessQuestions.find(q => q.id === 'fit-str-1')!,
      wellnessQuestions.find(q => q.id === 'fit-flex-2')!,
      wellnessQuestions.find(q => q.id === 'nut-plan-1')!,
      wellnessQuestions.find(q => q.id === 'nut-iq-2')!,
      wellnessQuestions.find(q => q.id === 'nut-hydro-1')!,
      wellnessQuestions.find(q => q.id === 'mind-focus-3')!,
      wellnessQuestions.find(q => q.id === 'mind-breath-2')!,
      wellnessQuestions.find(q => q.id === 'mind-med-2')!,
      wellnessQuestions.find(q => q.id === 'mind-stress-3')!,
      wellnessQuestions.find(q => q.id === 'sleep-opt-1')!,
      wellnessQuestions.find(q => q.id === 'sleep-sci-2')!,
      wellnessQuestions.find(q => q.id === 'sleep-hab-1')!,
      wellnessQuestions.find(q => q.id === 'sleep-dis-2')!,
      wellnessQuestions.find(q => q.id === 'sleep-dis-3')!,
    ],
    milestones: [
      { progress: 25, reward: 300 },
      { progress: 50, reward: 400 },
      { progress: 75, reward: 500 },
    ],
    leaderboard: [
      { playerName: 'WellnessKing', score: 15, rank: 'S', timestamp: new Date() },
      { playerName: 'HealthGuru', score: 14, rank: 'S', timestamp: new Date() },
      { playerName: 'FitnessElite', score: 13, rank: 'A', timestamp: new Date() },
    ],
  },
];

// All Available Achievements
export const allAchievements: Achievement[] = [
  {
    id: 'ach-first-quest',
    name: 'First Clear',
    description: 'Complete your first browser mini-game quest',
    icon: '🎯',
    category: 'quest',
    tier: 'bronze',
  },
  {
    id: 'ach-5-quests',
    name: 'Combo Starter',
    description: 'Complete 5 mini-game quests',
    icon: '⭐',
    category: 'quest',
    tier: 'bronze',
    target: 5,
  },
  {
    id: 'ach-25-quests',
    name: 'Arcade Veteran',
    description: 'Complete 25 mini-game quests',
    icon: '🌟',
    category: 'quest',
    tier: 'silver',
    target: 25,
  },
  {
    id: 'ach-100-quests',
    name: 'Legendary Grinder',
    description: 'Complete 100 mini-game quests',
    icon: '👑',
    category: 'quest',
    tier: 'gold',
    target: 100,
  },
  {
    id: 'ach-first-question',
    name: 'Quiz Novice',
    description: 'Complete your first wellness question quest',
    icon: '❓',
    category: 'quest',
    tier: 'bronze',
  },
  {
    id: 'ach-5-questions',
    name: 'Question Starter',
    description: 'Complete 5 wellness question quests',
    icon: '🧠',
    category: 'quest',
    tier: 'bronze',
    target: 5,
  },
  {
    id: 'ach-25-questions',
    name: 'Knowledge Seeker',
    description: 'Complete 25 wellness question quests',
    icon: '📚',
    category: 'quest',
    tier: 'silver',
    target: 25,
  },
  {
    id: 'ach-100-questions',
    name: 'Wellness Scholar',
    description: 'Complete 100 wellness question quests',
    icon: '🎓',
    category: 'quest',
    tier: 'gold',
    target: 100,
  },
  {
    id: 'ach-all-categories',
    name: 'Category Master',
    description: 'Complete question quests in all wellness categories (Fitness, Mindfulness, Nutrition, Sleep)',
    icon: '🌈',
    category: 'special',
    tier: 'gold',
  },
  {
    id: 'ach-3-streak',
    name: 'Win Streak I',
    description: 'Maintain a 3-day mini-game win streak',
    icon: '🔥',
    category: 'streak',
    tier: 'bronze',
    target: 3,
  },
  {
    id: 'ach-7-streak',
    name: 'Win Streak II',
    description: 'Maintain a 7-day mini-game win streak',
    icon: '💪',
    category: 'streak',
    tier: 'silver',
    target: 7,
  },
  {
    id: 'ach-streak-30',
    name: 'Unstoppable Queue',
    description: 'Maintain a 30-day mini-game win streak',
    icon: '⚡',
    category: 'streak',
    tier: 'gold',
    target: 30,
  },
  {
    id: 'ach-100-streak',
    name: 'Ranked Immortal',
    description: 'Maintain a 100-day mini-game win streak',
    icon: '💎',
    category: 'streak',
    tier: 'platinum',
    target: 100,
  },
  {
    id: 'ach-10km',
    name: 'Runner Bronze',
    description: 'Run a cumulative 10km through mini-game clears',
    icon: '🏃',
    category: 'distance',
    tier: 'bronze',
    target: 10,
  },
  {
    id: 'ach-50km',
    name: 'Runner Silver',
    description: 'Run a cumulative 50km through mini-game clears',
    icon: '🏃‍♂️',
    category: 'distance',
    tier: 'silver',
    target: 50,
  },
  {
    id: 'ach-100km',
    name: 'Runner Gold',
    description: 'Run a cumulative 100km through mini-game clears',
    icon: '🎖️',
    category: 'distance',
    tier: 'gold',
    target: 100,
  },
  {
    id: 'ach-level-5',
    name: 'Rookie Rank',
    description: 'Reach level 5',
    icon: '📈',
    category: 'level',
    tier: 'bronze',
    target: 5,
  },
  {
    id: 'ach-level-10',
    name: 'Challenger Rank',
    description: 'Reach level 10',
    icon: '📊',
    category: 'level',
    tier: 'silver',
    target: 10,
  },
  {
    id: 'ach-level-25',
    name: 'Elite Rank',
    description: 'Reach level 25',
    icon: '🏆',
    category: 'level',
    tier: 'gold',
    target: 25,
  },
  {
    id: 'ach-level-50',
    name: 'Mythic Rank',
    description: 'Reach level 50',
    icon: '👑',
    category: 'level',
    tier: 'platinum',
    target: 50,
  },
  {
    id: 'ach-mindful',
    name: 'Zen Rhythm Master',
    description: 'Complete 20 mindfulness mini-game clears',
    icon: '🧘',
    category: 'special',
    tier: 'gold',
    target: 20,
  },
  {
    id: 'ach-balanced',
    name: 'Mode Master',
    description: 'Clear quests in all 4 mini-game modes',
    icon: '⚖️',
    category: 'special',
    tier: 'silver',
  },
];

// Enhanced quests with recommendations
export const enhancedQuests: Quest[] = [
  {
    id: 'quest-1',
    title: 'Runner Tutorial',
    description: 'Play the fitness runner mini-game and clear the tutorial lane',
    type: 'fitness',
    difficulty: 'easy',
    rewards: { experience: 30, gold: 15 },
    requirements: 'Clear 1 fitness mini-game run',
    completed: false,
    recommendedFor: ['beginner', 'balanced'],
  },
  {
    id: 'quest-2',
    title: 'Sprint Circuit',
    description: 'Clear a full 3km run in the fitness mini-game',
    type: 'fitness',
    difficulty: 'easy',
    rewards: { experience: 50, gold: 25 },
    requirements: 'Finish 3km in the runner mini-game',
    completed: false,
    recommendedFor: ['active', 'athlete'],
  },
  {
    id: 'quest-3',
    title: 'Calm Clicker',
    description: 'Complete a short mindfulness breathing mini-game session',
    type: 'mindfulness',
    difficulty: 'easy',
    rewards: { experience: 40, gold: 20 },
    requirements: 'Clear 1 mindfulness mini-game session',
    completed: false,
    recommendedFor: ['beginner', 'balanced', 'health-focused'],
  },
  {
    id: 'quest-4',
    title: 'Breath Boss',
    description: 'Chain perfect breaths in the advanced mindfulness mini-game',
    type: 'mindfulness',
    difficulty: 'medium',
    rewards: { experience: 80, gold: 40 },
    requirements: 'Clear 1 advanced mindfulness mini-game session',
    completed: false,
    recommendedFor: ['health-focused', 'balanced'],
  },
  {
    id: 'quest-5',
    title: 'Plate Builder',
    description: 'Build a complete healthy plate in the nutrition mini-game',
    type: 'nutrition',
    difficulty: 'easy',
    rewards: { experience: 35, gold: 18 },
    requirements: 'Match 3 healthy foods in the nutrition mini-game',
    completed: false,
    recommendedFor: ['beginner', 'health-focused', 'balanced'],
  },
  {
    id: 'quest-6',
    title: 'Macro Stacker',
    description: 'Win multiple rounds of the nutrition mini-game back-to-back',
    type: 'nutrition',
    difficulty: 'medium',
    rewards: { experience: 75, gold: 40 },
    requirements: 'Clear 3 nutrition mini-game rounds',
    completed: false,
    recommendedFor: ['health-focused', 'active', 'athlete'],
  },
  {
    id: 'quest-7',
    title: 'Sheep Starter',
    description: 'Play the sleep mini-game and reach your first calm streak',
    type: 'sleep',
    difficulty: 'easy',
    rewards: { experience: 40, gold: 20 },
    requirements: 'Count 10 sheep in the sleep mini-game',
    completed: false,
    recommendedFor: ['beginner', 'balanced'],
  },
  {
    id: 'quest-8',
    title: 'Night Mode Clear',
    description: 'Complete an extended sleep mini-game run without resets',
    type: 'sleep',
    difficulty: 'medium',
    rewards: { experience: 60, gold: 35 },
    requirements: 'Clear sleep mini-game in one run',
    completed: false,
    recommendedFor: ['health-focused', 'balanced', 'athlete'],
  },
  {
    id: 'quest-9',
    title: 'Power Lane',
    description: 'Beat the hard fitness mini-game lane',
    type: 'fitness',
    difficulty: 'hard',
    rewards: { experience: 100, gold: 60 },
    requirements: 'Clear hard fitness mini-game',
    completed: false,
    recommendedFor: ['athlete', 'active'],
  },
  {
    id: 'quest-10',
    title: 'Turbo Rush',
    description: 'Complete the elite fitness mini-game at high pace',
    type: 'fitness',
    difficulty: 'hard',
    rewards: { experience: 120, gold: 70 },
    requirements: 'Clear elite fitness mini-game',
    completed: false,
    recommendedFor: ['athlete', 'active'],
  },
  {
    id: 'quest-11',
    title: 'Flow State',
    description: 'Complete a long mindfulness mini-game flow session',
    type: 'mindfulness',
    difficulty: 'medium',
    rewards: { experience: 70, gold: 35 },
    requirements: 'Clear extended mindfulness mini-game',
    completed: false,
    recommendedFor: ['balanced', 'health-focused', 'active'],
  },
  {
    id: 'quest-12',
    title: 'Kitchen Grandmaster',
    description: 'Beat the hardest nutrition mini-game challenge set',
    type: 'nutrition',
    difficulty: 'hard',
    rewards: { experience: 150, gold: 80 },
    requirements: 'Clear hard nutrition mini-game',
    completed: false,
    recommendedFor: ['athlete', 'health-focused'],
  },
  {
    id: 'quest-13',
    title: 'Tempo Crusher',
    description: 'Dominate a high-tempo fitness mini-game set with steady precision',
    type: 'fitness',
    difficulty: 'medium',
    rewards: { experience: 90, gold: 50 },
    requirements: 'Clear 2 high-tempo fitness mini-game rounds',
    completed: false,
    recommendedFor: ['active', 'athlete'],
  },
  {
    id: 'quest-14',
    title: 'Endurance Blitz',
    description: 'Survive an extended elite fitness mini-game run',
    type: 'fitness',
    difficulty: 'hard',
    rewards: { experience: 145, gold: 85 },
    requirements: 'Clear extended elite fitness mini-game',
    completed: false,
    recommendedFor: ['athlete', 'active'],
  },
  {
    id: 'quest-15',
    title: 'Zen Pulse',
    description: 'Maintain perfect calm and complete an advanced mindfulness flow',
    type: 'mindfulness',
    difficulty: 'hard',
    rewards: { experience: 130, gold: 72 },
    requirements: 'Clear advanced mindfulness flow mini-game',
    completed: false,
    recommendedFor: ['health-focused', 'balanced', 'athlete'],
  },
  {
    id: 'quest-16',
    title: 'Macro Marathon',
    description: 'Conquer a long nutrition mini-game session with minimal mistakes',
    type: 'nutrition',
    difficulty: 'hard',
    rewards: { experience: 140, gold: 78 },
    requirements: 'Clear long-form nutrition mini-game challenge',
    completed: false,
    recommendedFor: ['health-focused', 'athlete', 'active'],
  },
  {
    id: 'quest-17',
    title: 'Dream Starter+',
    description: 'Execute a complete bedtime sequence in the sleep mini-game',
    type: 'sleep',
    difficulty: 'medium',
    rewards: { experience: 85, gold: 46 },
    requirements: 'Finish sleep routine sequence without resets',
    completed: false,
    recommendedFor: ['balanced', 'health-focused'],
  },
  {
    id: 'quest-18',
    title: 'Deep Night Protocol',
    description: 'Complete the hardest sleep mini-game run in one focused attempt',
    type: 'sleep',
    difficulty: 'hard',
    rewards: { experience: 135, gold: 74 },
    requirements: 'Clear hard sleep mini-game mode',
    completed: false,
    recommendedFor: ['health-focused', 'athlete', 'balanced'],
  },
];

// Question-Based Quests - Answer simple questions
export const questionBasedQuests: Quest[] = [
  {
    id: 'qquest-1',
    title: 'Fitness Fundamentals',
    description: 'Answer 5 questions about fitness basics',
    type: 'fitness',
    difficulty: 'easy',
    rewards: { experience: 25, gold: 12 },
    requirements: 'Answer 5 fitness questions correctly',
    completed: false,
    recommendedFor: ['beginner', 'balanced'],
    questions: [
      wellnessQuestions.find(q => q.id === 'fit-str-2')!,
      wellnessQuestions.find(q => q.id === 'fit-str-3')!,
      wellnessQuestions.find(q => q.id === 'fit-flex-1')!,
      wellnessQuestions.find(q => q.id === 'fit-sprint-2')!,
      wellnessQuestions.find(q => q.id === 'fit-str-1')!,
    ],
  },
  {
    id: 'qquest-2',
    title: 'Cardio Knowledge',
    description: 'Test your cardio and heart health knowledge with 5 questions',
    type: 'fitness',
    difficulty: 'medium',
    rewards: { experience: 60, gold: 30 },
    requirements: 'Answer 5 cardio quiz questions',
    completed: false,
    recommendedFor: ['active', 'health-focused'],
    questions: [
      wellnessQuestions.find(q => q.id === 'fit-sprint-1')!,
      wellnessQuestions.find(q => q.id === 'fit-sprint-2')!,
      wellnessQuestions.find(q => q.id === 'fit-sprint-3')!,
      wellnessQuestions.find(q => q.id === 'fit-flex-2')!,
      wellnessQuestions.find(q => q.id === 'fit-str-3')!,
    ],
  },
  {
    id: 'qquest-3',
    title: 'Mindfulness Basics',
    description: 'Learn mindfulness with 5 simple questions',
    type: 'mindfulness',
    difficulty: 'easy',
    rewards: { experience: 35, gold: 18 },
    requirements: 'Answer 5 mindfulness questions',
    completed: false,
    recommendedFor: ['beginner', 'balanced', 'health-focused'],
    questions: [
      wellnessQuestions.find(q => q.id === 'mind-focus-1')!,
      wellnessQuestions.find(q => q.id === 'mind-focus-2')!,
      wellnessQuestions.find(q => q.id === 'mind-med-1')!,
      wellnessQuestions.find(q => q.id === 'mind-stress-1')!,
      wellnessQuestions.find(q => q.id === 'mind-focus-4')!,
    ],
  },
  {
    id: 'qquest-4',
    title: 'Breathing Techniques',
    description: 'Master breathing techniques with 5 detailed questions',
    type: 'mindfulness',
    difficulty: 'medium',
    rewards: { experience: 55, gold: 28 },
    requirements: 'Answer 5 breathing technique questions',
    completed: false,
    recommendedFor: ['health-focused', 'balanced'],
    questions: [
      wellnessQuestions.find(q => q.id === 'mind-breath-1')!,
      wellnessQuestions.find(q => q.id === 'mind-breath-2')!,
      wellnessQuestions.find(q => q.id === 'mind-breath-3')!,
      wellnessQuestions.find(q => q.id === 'mind-stress-2')!,
      wellnessQuestions.find(q => q.id === 'mind-med-3')!,
    ],
  },
  {
    id: 'qquest-5',
    title: 'Nutrition Starter',
    description: 'Start your nutrition journey with 5 basic food questions',
    type: 'nutrition',
    difficulty: 'easy',
    rewards: { experience: 30, gold: 15 },
    requirements: 'Answer 5 nutrition questions',
    completed: false,
    recommendedFor: ['beginner', 'health-focused', 'balanced'],
    questions: [
      wellnessQuestions.find(q => q.id === 'nut-iq-1')!,
      wellnessQuestions.find(q => q.id === 'nut-hydro-2')!,
      wellnessQuestions.find(q => q.id === 'nut-plan-2')!,
      wellnessQuestions.find(q => q.id === 'nut-iq-3')!,
      wellnessQuestions.find(q => q.id === 'nut-hydro-1')!,
    ],
  },
  {
    id: 'qquest-6',
    title: 'Macro Master',
    description: 'Test your knowledge of macronutrients with 5 questions',
    type: 'nutrition',
    difficulty: 'medium',
    rewards: { experience: 70, gold: 35 },
    requirements: 'Answer 5 macronutrient questions',
    completed: false,
    recommendedFor: ['health-focused', 'active', 'athlete'],
    questions: [
      wellnessQuestions.find(q => q.id === 'nut-plan-1')!,
      wellnessQuestions.find(q => q.id === 'nut-plan-2')!,
      wellnessQuestions.find(q => q.id === 'nut-iq-2')!,
      wellnessQuestions.find(q => q.id === 'nut-plan-3')!,
      wellnessQuestions.find(q => q.id === 'nut-iq-1')!,
    ],
  },
  {
    id: 'qquest-7',
    title: 'Sleep Science 101',
    description: 'Learn sleep science basics with 5 questions',
    type: 'sleep',
    difficulty: 'easy',
    rewards: { experience: 40, gold: 20 },
    requirements: 'Answer 5 sleep science questions',
    completed: false,
    recommendedFor: ['beginner', 'balanced'],
    questions: [
      wellnessQuestions.find(q => q.id === 'sleep-opt-2')!,
      wellnessQuestions.find(q => q.id === 'sleep-opt-3')!,
      wellnessQuestions.find(q => q.id === 'sleep-hab-2')!,
      wellnessQuestions.find(q => q.id === 'sleep-dis-1')!,
      wellnessQuestions.find(q => q.id === 'sleep-hab-3')!,
    ],
  },
  {
    id: 'qquest-8',
    title: 'Sleep Optimization',
    description: 'Optimize your sleep with 5 advanced sleep questions',
    type: 'sleep',
    difficulty: 'medium',
    rewards: { experience: 65, gold: 32 },
    requirements: 'Answer 5 sleep optimization questions',
    completed: false,
    recommendedFor: ['health-focused', 'balanced'],
    questions: [
      wellnessQuestions.find(q => q.id === 'sleep-opt-1')!,
      wellnessQuestions.find(q => q.id === 'sleep-sci-1')!,
      wellnessQuestions.find(q => q.id === 'sleep-sci-2')!,
      wellnessQuestions.find(q => q.id === 'sleep-hab-1')!,
      wellnessQuestions.find(q => q.id === 'sleep-hab-2')!,
    ],
  },
  {
    id: 'qquest-9',
    title: 'Strength Science',
    description: 'Answer advanced strength and recovery questions',
    type: 'fitness',
    difficulty: 'hard',
    rewards: { experience: 85, gold: 42 },
    requirements: 'Answer 5 advanced fitness questions',
    completed: false,
    recommendedFor: ['active', 'athlete'],
    questions: [
      wellnessQuestions.find(q => q.id === 'fit-sprint-3')!,
      wellnessQuestions.find(q => q.id === 'fit-str-1')!,
      wellnessQuestions.find(q => q.id === 'fit-str-3')!,
      wellnessQuestions.find(q => q.id === 'fit-flex-2')!,
      wellnessQuestions.find(q => q.id === 'fit-sprint-1')!,
    ],
  },
  {
    id: 'qquest-10',
    title: 'Mobility & Form',
    description: 'Build better movement quality with flexibility and form knowledge',
    type: 'fitness',
    difficulty: 'medium',
    rewards: { experience: 62, gold: 31 },
    requirements: 'Answer 5 mobility and form questions',
    completed: false,
    recommendedFor: ['beginner', 'balanced', 'active'],
    questions: [
      wellnessQuestions.find(q => q.id === 'fit-flex-1')!,
      wellnessQuestions.find(q => q.id === 'fit-flex-2')!,
      wellnessQuestions.find(q => q.id === 'fit-str-2')!,
      wellnessQuestions.find(q => q.id === 'fit-str-3')!,
      wellnessQuestions.find(q => q.id === 'fit-sprint-2')!,
    ],
  },
  {
    id: 'qquest-11',
    title: 'Mind Resilience',
    description: 'Train mental resilience with stress and mindfulness questions',
    type: 'mindfulness',
    difficulty: 'hard',
    rewards: { experience: 88, gold: 44 },
    requirements: 'Answer 5 resilience and stress-management questions',
    completed: false,
    recommendedFor: ['health-focused', 'balanced', 'athlete'],
    questions: [
      wellnessQuestions.find(q => q.id === 'mind-stress-1')!,
      wellnessQuestions.find(q => q.id === 'mind-stress-2')!,
      wellnessQuestions.find(q => q.id === 'mind-stress-3')!,
      wellnessQuestions.find(q => q.id === 'mind-med-2')!,
      wellnessQuestions.find(q => q.id === 'mind-breath-2')!,
    ],
  },
  {
    id: 'qquest-12',
    title: 'Meditation Mastery',
    description: 'Level up meditation technique and consistency knowledge',
    type: 'mindfulness',
    difficulty: 'medium',
    rewards: { experience: 66, gold: 33 },
    requirements: 'Answer 5 meditation and focus questions',
    completed: false,
    recommendedFor: ['balanced', 'health-focused', 'active'],
    questions: [
      wellnessQuestions.find(q => q.id === 'mind-med-1')!,
      wellnessQuestions.find(q => q.id === 'mind-med-2')!,
      wellnessQuestions.find(q => q.id === 'mind-med-3')!,
      wellnessQuestions.find(q => q.id === 'mind-focus-3')!,
      wellnessQuestions.find(q => q.id === 'mind-focus-4')!,
    ],
  },
  {
    id: 'qquest-13',
    title: 'Hydration & Recovery',
    description: 'Master hydration and recovery fueling strategies',
    type: 'nutrition',
    difficulty: 'medium',
    rewards: { experience: 64, gold: 32 },
    requirements: 'Answer 5 hydration and recovery questions',
    completed: false,
    recommendedFor: ['health-focused', 'active', 'balanced'],
    questions: [
      wellnessQuestions.find(q => q.id === 'nut-hydro-1')!,
      wellnessQuestions.find(q => q.id === 'nut-hydro-2')!,
      wellnessQuestions.find(q => q.id === 'nut-plan-3')!,
      wellnessQuestions.find(q => q.id === 'nut-iq-3')!,
      wellnessQuestions.find(q => q.id === 'nut-plan-2')!,
    ],
  },
  {
    id: 'qquest-14',
    title: 'Performance Nutrition',
    description: 'Test high-performance nutrition strategy knowledge',
    type: 'nutrition',
    difficulty: 'hard',
    rewards: { experience: 92, gold: 46 },
    requirements: 'Answer 5 advanced nutrition strategy questions',
    completed: false,
    recommendedFor: ['athlete', 'health-focused', 'active'],
    questions: [
      wellnessQuestions.find(q => q.id === 'nut-plan-1')!,
      wellnessQuestions.find(q => q.id === 'nut-plan-2')!,
      wellnessQuestions.find(q => q.id === 'nut-plan-3')!,
      wellnessQuestions.find(q => q.id === 'nut-iq-2')!,
      wellnessQuestions.find(q => q.id === 'nut-hydro-1')!,
    ],
  },
  {
    id: 'qquest-15',
    title: 'Sleep Recovery Lab',
    description: 'Deepen your sleep recovery science knowledge',
    type: 'sleep',
    difficulty: 'hard',
    rewards: { experience: 90, gold: 45 },
    requirements: 'Answer 5 advanced sleep science questions',
    completed: false,
    recommendedFor: ['health-focused', 'athlete', 'balanced'],
    questions: [
      wellnessQuestions.find(q => q.id === 'sleep-sci-1')!,
      wellnessQuestions.find(q => q.id === 'sleep-sci-2')!,
      wellnessQuestions.find(q => q.id === 'sleep-dis-2')!,
      wellnessQuestions.find(q => q.id === 'sleep-dis-3')!,
      wellnessQuestions.find(q => q.id === 'sleep-opt-1')!,
    ],
  },
  {
    id: 'qquest-16',
    title: 'Sleep Hygiene Masterclass',
    description: 'Sharpen your nightly routine strategy with practical sleep questions',
    type: 'sleep',
    difficulty: 'medium',
    rewards: { experience: 68, gold: 34 },
    requirements: 'Answer 5 sleep habit and optimization questions',
    completed: false,
    recommendedFor: ['beginner', 'balanced', 'health-focused'],
    questions: [
      wellnessQuestions.find(q => q.id === 'sleep-hab-1')!,
      wellnessQuestions.find(q => q.id === 'sleep-hab-2')!,
      wellnessQuestions.find(q => q.id === 'sleep-hab-3')!,
      wellnessQuestions.find(q => q.id === 'sleep-opt-3')!,
      wellnessQuestions.find(q => q.id === 'sleep-dis-1')!,
    ],
  },
];

// Game-Based Tier Challenges - Track Mini-Game Completions
export const gameTierChallenges: Challenge[] = [
  // Daily Challenges - Mini-Game Based
  {
    id: 'game-daily-1',
    name: '🏃 Sprint Master',
    description: 'Complete 4 perfect fitness mini-game sessions',
    type: 'fitness',
    tier: 'daily',
    difficulty: 'normal',
    target: 4,
    current: 0,
    unit: 'perfect sessions',
    startDate: new Date(),
    endDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    reward: {
      experience: 300,
      gold: 150,
    },
    completed: false,
    claimed: false,
    participants: 4521,
    modifier: 'perfect-only',
  },
  {
    id: 'game-daily-2',
    name: '🧠 Mind Clarity',
    description: 'Complete 4 mindfulness mini-game sessions',
    type: 'mindfulness',
    tier: 'daily',
    difficulty: 'normal',
    target: 4,
    current: 0,
    unit: 'sessions',
    startDate: new Date(),
    endDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    reward: {
      experience: 250,
      gold: 120,
    },
    completed: false,
    claimed: false,
    participants: 3892,
  },
  {
    id: 'game-daily-3',
    name: '🥗 Plate Builder',
    description: 'Build 4 perfect healthy plates',
    type: 'nutrition',
    tier: 'daily',
    difficulty: 'normal',
    target: 4,
    current: 0,
    unit: 'perfect meals',
    startDate: new Date(),
    endDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    reward: {
      experience: 280,
      gold: 140,
    },
    completed: false,
    claimed: false,
    participants: 5234,
    modifier: 'perfect-only',
  },
  {
    id: 'game-daily-4',
    name: '😴 Dream Catcher',
    description: 'Complete 4 sleep mini-game sessions',
    type: 'sleep',
    tier: 'daily',
    difficulty: 'normal',
    target: 4,
    current: 0,
    unit: 'sessions',
    startDate: new Date(),
    endDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    reward: {
      experience: 270,
      gold: 130,
    },
    completed: false,
    claimed: false,
    participants: 2876,
  },

  // Weekly Challenges - Mini-Game Based
  {
    id: 'game-weekly-1',
    name: '💪 Fitness Beast',
    description: 'Complete 10 S-rank fitness mini-games',
    type: 'fitness',
    tier: 'weekly',
    difficulty: 'hard',
    target: 10,
    current: 0,
    unit: 'S-ranks',
    startDate: new Date(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    reward: {
      experience: 1200,
      gold: 600,
      achievement: 'ach-fitness-beast',
    },
    completed: false,
    claimed: false,
    participants: 1243,
  },
  {
    id: 'game-weekly-2',
    name: '🎯 Zen Master',
    description: 'Achieve 15 A+ ranks in mindfulness mini-games',
    type: 'mindfulness',
    tier: 'weekly',
    difficulty: 'hard',
    target: 15,
    current: 0,
    unit: 'A-ranks',
    startDate: new Date(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    reward: {
      experience: 1100,
      gold: 550,
      achievement: 'ach-zen-master',
    },
    completed: false,
    claimed: false,
    participants: 987,
  },
  {
    id: 'game-weekly-3',
    name: '🍽️ Nutrition Expert',
    description: 'Complete 8 S-rank nutrition mini-games',
    type: 'nutrition',
    tier: 'weekly',
    difficulty: 'hard',
    target: 8,
    current: 0,
    unit: 'S-ranks',
    startDate: new Date(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    reward: {
      experience: 1050,
      gold: 520,
      achievement: 'ach-nutrition-expert',
    },
    completed: false,
    claimed: false,
    participants: 1567,
  },
  {
    id: 'game-weekly-4',
    name: '🌙 Sleep Scholar',
    description: 'Complete 12 sessions of sleep mini-games',
    type: 'sleep',
    tier: 'weekly',
    difficulty: 'normal',
    target: 12,
    current: 0,
    unit: 'sessions',
    startDate: new Date(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    reward: {
      experience: 950,
      gold: 475,
    },
    completed: false,
    claimed: false,
    participants: 2134,
  },
];

// Generate personalized starting item based on wellness survey
export const createPersonalizedStartingItem = (
  primaryStat: 'fitness' | 'nutrition' | 'mindfulness' | 'sleep'
): Omit<InventoryItem, 'id'> => {
  const personalizationMap = {
    fitness: {
      name: '⚡ Fitness Ring',
      description: 'A powerful ring imbued with the essence of physical strength. Grants bonus experience on fitness games.',
      type: 'accessory' as const,
      rarity: 'rare' as const,
      quantity: 1,
      buffs: {
        xpMultiplier: 1.5,
      },
    },
    nutrition: {
      name: '🥗 Nutritionist\'s Badge',
      description: 'A prestigious badge earned by those who master nutrition. Grants bonus experience on nutrition games.',
      type: 'accessory' as const,
      rarity: 'rare' as const,
      quantity: 1,
      buffs: {
        xpMultiplier: 1.5,
      },
    },
    mindfulness: {
      name: '🧘 Serenity Amulet',
      description: 'An ancient amulet that enhances mindfulness and inner peace. Grants bonus experience on mindfulness games.',
      type: 'accessory' as const,
      rarity: 'rare' as const,
      quantity: 1,
      buffs: {
        xpMultiplier: 1.5,
      },
    },
    sleep: {
      name: '😴 Dream Weaver\'s Charm',
      description: 'A magical charm that protects your sleep cycle. Grants bonus experience on sleep games.',
      type: 'accessory' as const,
      rarity: 'rare' as const,
      quantity: 1,
      buffs: {
        xpMultiplier: 1.5,
      },
    },
  };

  return personalizationMap[primaryStat];
};

